apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - services.yaml
  - deployments.yaml
  - pdb-hpa.yaml
  - ingress.yaml
  - migration-configmap.yaml
  - migration-job.yaml

labels:
  - pairs:
      app.kubernetes.io/name: usfarcade
      app.kubernetes.io/managed-by: kustomize
